# NOTE: this example targets the master branch of i3status-rust.
#
# For latest stable version, refer to
# https://github.com/greshake/i3status-rust/blob/v0.22.0/examples/config.toml

[icons]
name = "material-nf"

[theme]
name = "dracula"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[[block]]
block = "custom"
command = "cat ~/.meta/status/pomodoro"
watch_files = ["~/.meta/status/pomodoro"]
interval = "once"
hide_when_empty = true
[block.theme_overrides]
idle_bg = "#ffa500"
idle_fg = "#123456"

[[block]]
block = "custom"
command = "cat ~/.meta/status/onedrive"
watch_files = ["~/.meta/status/onedrive"]
interval = "once"
hide_when_empty = true
[block.theme_overrides]
idle_bg = "#abcdef"
idle_fg = "#123456"

[[block]]
block = "custom"
command = "~/.config/i3status-rust/scripts/onedrive"
interval = 300
hide_when_empty = true

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 600
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "sound"
step_width = 5
on_click = "pavucontrol"

[[block]]
block = "time"
interval = 10
format = "%a %d/%m %R"

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ['br\-[0-9a-f]{12}', 'docker\d+']
interface_name_include = []
ap_format = "{strength} {ssid^10}"
device_format = "{icon} {ap}"

[[block]]
block = "battery"
if_command = "test -e /sys/class/power_supply/BAT0"
